language: go
sudo: false
go:
  - "1.11.x"

install:
  - go get -t ./...
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls


script:
  - $HOME/gopath/bin/goveralls -service=travis-ci

notifications:
      email: false
